{{- if .Values.apps.fuhrimanWebsite.enabled }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: fuhriman-website
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "0"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: {{ .Values.spec.source.repoURL }}
    path: fuhriman-chart
    targetRevision: {{ .Values.spec.source.targetRevision }}
  destination:
    server: {{ .Values.spec.destination.server }}
    namespace: {{ .Values.apps.fuhrimanWebsite.namespace }}
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
{{- end }}
